### ISSUE TITLE
Error with --mode readlength

### ISSUE THREAD

**Issue by thalescherubino** [MikeAxtell/ShortTracks#2]
Hi Mike

I am trying to run ShortTracks with bam files produced by ShortStack4.
I am using samtools 1.3.1 and i am getting the following error with --mode readlength:

samtools view -F 272 -e "qlen==21" -h G4_Sir_bud36l_r1.bam | samtools depth - > G4_Sir_bud36l_r1_21_p_depths.txt
view: invalid option -- 'e'
[E::hts_open_format] fail to open file 'qlen==21'
samtools view: failed to open "qlen==21" for reading: No such file or directory

Should I use other version of samtools with the -e option?

**Comment by MikeAxtell** [comment]
Yes, that is likely a very out of date version of samtools that doesn't support '-e' filtering expressions.

From: thalescherubino ***@***.***>
Date: Thursday, May 18, 2023 at 2:52 PM
To: MikeAxtell/ShortTracks ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MikeAxtell/ShortTracks] Error with --mode readlength (Issue #2)

Hi Mike

I am trying to run ShortTracks with bam files produced by ShortStack4.
I am using samtools 1.3.1 and i am getting the following error with --mode readlength:

samtools view -F 272 -e "qlen==21" -h G4_Sir_bud36l_r1.bam | samtools depth - > G4_Sir_bud36l_r1_21_p_depths.txt
view: invalid option -- 'e'
[E::hts_open_format] fail to open file 'qlen==21'
samtools view: failed to open "qlen==21" for reading: No such file or directory

Should I use other version of samtools with the -e option?
